name: Spent
options:
  bundleIdPrefix: com.spent
  deploymentTarget:
    iOS: "16.1"

targets:
  Spent:
    type: application
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: Spent
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spent.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Spent/Info.plist
        CODE_SIGN_ENTITLEMENTS: Spent/Spent.entitlements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: SpentActivityReport
      - sdk: DeviceActivity.framework
      - sdk: FamilyControls.framework

  SpentActivityReport:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: SpentActivityReport
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spent.app.activityreport
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: SpentActivityReport/Info.plist
        CODE_SIGN_ENTITLEMENTS: SpentActivityReport/Extension.entitlements
    dependencies:
      - sdk: DeviceActivity.framework
      - sdk: FamilyControls.framework
